name: Docker

on:
  push:

jobs:
  publish:
    # Build and push Docker image (only master branch or new tags, no pull requests).
    if: (endsWith(github.ref, '/master') || startsWith(github.ref, 'refs/tags/')) && contains(github.event_name, 'pull_request') == false
    name: Push updated version to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: claudiugeorgiu
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: index.docker.io/claudiugeorgiu/python-texlive
          tags: |
            type=raw,value=latest
            type=ref,event=tag

      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          sbom: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Generate Docker image attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/claudiugeorgiu/python-texlive
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
