name: Docker

on:
  push:

jobs:
  publish:
    # Build and push Docker image (only master branch or new tags, no pull requests).
    if: (endsWith(github.ref, '/master') || startsWith(github.ref, 'refs/tags/')) && contains(github.event_name, 'pull_request') == false
    name: Push updated version to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: claudiugeorgiu
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: claudiugeorgiu/python-texlive
          tags: |
            type=raw,value=latest
            type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
